/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import treeModel from './models/tree.gltf';

const Tree = ({
  position = [0, 24, 0],
  rotation = [-3.13, -0.42, 3.08],
  scale= [10, 10, 10]
}) => {
  const group = useRef();
  const { nodes, materials } = useGLTF(treeModel);
  
  return (
    <group ref={group} dispose={null}>
      <group position={position} rotation={rotation} scale={scale}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  );
};

export default Tree;

useGLTF.preload('/tree.gltf')
