/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import WheatPlanterModel from "./models/wheatPlanter.gltf";
import WheatCrop from "./WheatCrop";

const WheatPlanter = ({ ...props }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF(WheatPlanterModel);

  const wheatSet = [];

  for (let i = 0; i < 5; i++) {
    for (let j = 0; j < 5; j++) {
      wheatSet.push(
        <WheatCrop
          key={`wheat_crop_${i + j * 10}`}
          scale={[0.4, 0.4, 0.4]}
          position={[0.4 + i * 0.8, 0, -1.5 - j * 0.8]}
        />
      );
    }
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[0, 0, -2]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[2, 0, -2]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[0.23, 0.64, -5.23]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.5, 5.5, 0.5]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={nodes.Cylinder013.material}
        position={[4.77, 0.64, -5.23]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.5, 5.5, 0.5]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={nodes.Cylinder014.material}
        position={[-0.25, 0.82, -4.76]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.5, 5.5, 0.5]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={nodes.Cylinder015.material}
        position={[-0.25, 0.82, -0.25]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.5, 5.5, 0.5]}
      />
      {wheatSet}
    </group>
  );
};

export default WheatPlanter;

useGLTF.preload(WheatPlanterModel);
